services:
    anavaro.activenotifications.maincontroller:
        class: 'anavaro\activenotifications\controller\main_controller'
        arguments:
            - '@user'
            - '@config'
            - '@request'
            - '@notification_manager'
            - '%tables.notifications%'
            - '@dbal.conn'
            - '@template'
            - '@path_helper'
    anavaro.activenotifications.listener:
        class: 'anavaro\activenotifications\event\listener'
        arguments:
            - '@config'
            - '@user'
            - '@template'
            - '@notification_manager'
            - '@request'
            - '@symfony_request'
            - '@controller.helper'
        tags:
            - { name: 'event.listener' }
